### ISSUE TITLE
Add mod

### ISSUE THREAD

**Issue by lennart-hendriksma** [PBoer90/CSGO_Server#2]
Weapons Paints:
https://github.com/Franc1sco/Franug-Weapon_Paints

**Comment by PBoer90** [comment]
Is een leuke inderdaad, het enige nadeel is dat je daarvoor een Ban krijgt van Valve, including 4 weken comp. ban.

**Comment by lennart-hendriksma** [comment]
Op jou account of op de server??

**Comment by PBoer90** [comment]
Op je account, aangezien daar mijn server-token is geregistreerd.
